### ISSUE TITLE
Please rename this to include TOTP / 2FA and avoid being Google-specific.

### ISSUE THREAD

**Issue by MagicFab** [sysPass/plugin-Authenticator#10]
It would be useful to be as inclusive as possible in this plugin description.

By indicating only that it works "with Google Authenticator" this may give the impression it **only** works with GA.

Other applications that this may work with, as I understand it, are KeepassXC, AndOTP, etc.

I would propose "Plugin to add two factor authentication (2FA) support to sysPass login for applications that implement Time-based One-time Password Algorithm (TOTP) as specified in RFC 6238.

This has been tested with AndOTP, KeepassXC, Google Authenticator."

... or similar

**Comment by nuxsmin** [comment]
Hello, I agree and I didn't describe so because this plugin hasn't been tested using other applications than GA.

As soon as it's tested I'll describe as pointed.

Thanks for the feedback!

Regards

**Comment by nuxsmin** [comment]
Sorry if I misunderstood you, but did you test it with these applications?

**Comment by MagicFab** [comment]
If it works with GA it will work with them. I will test on my setup.

**Comment by MagicFab** [comment]
I apologize as I see my initial report wasn't specific.

I see the README was updated, that's great, however this was about the plugin description which still indicates "Google Authenticator plugin for sysPass http://syspass.org"

**Comment by nuxsmin** [comment]
No worries...I've just updated the repo's description ;)

Thanks for the feedback!
