### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by fbernard89** [sysPass/plugin-Authenticator#11]
Hello,

We just start with this project and we install a fresh copy of the server with composer. After we use composer to list the available package (composer suggest) and pick league/oauth2-google, install dependency and everything go fine. Login with admin, enable the plugin, create a test user, connecting with the test user, edit the profile for enabling 2FA, scan QR code and activate it, logout and try to login and get this error 
There was an error
SyntaxError: Unexpected token C in JSON at position 0

Call to undefined method SP\Core\Events\EventMessage::getData()

Do you have any idea ?

Thanks !

**Comment by schleyk** [comment]
same problem :(

**Comment by nuxsmin** [comment]
Hello, I'll check it out for any wrong behavior.

Regards

**Comment by fbernard89** [comment]
Hello nuxsmin,

For your information the version installed is 3.0-rc8 (I can't install only the 3.0, composer always get the last version)

Thanks,

**Comment by schleyk** [comment]
Hi, I use the last stable docker image nuxsmin/docker-syspass:3.0-php7.2.

**Comment by ortizleo** [comment]
Hi.
Same problem here using last sysPass 3.0 release.
Php.7.1, Apache 2.4

**Comment by nuxsmin** [comment]
@fbernard89 could you tell me if there is any error logged in `syspass.log` file (you can download it from `config > information` tab)?

Regards

**Comment by schleyk** [comment]
To reproduce it you can install the `nuxsmin/docker-syspass:3.0-php7.2` docker Image and jump inside the container and run following:
```
root@81111e60e317:/var/www/html/sysPass# composer require syspass/plugin-authenticator
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^2.0 for syspass/plugin-authenticator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing syspass/plugin-authenticator (v2.0.0): Downloading (100%) Package phpunit/dbunit is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
```

**Comment by nuxsmin** [comment]
Though it's for debugging purpose, please you shouldn't run any extra commands within a container. You can use `COMPOSER_EXTENSIONS` environment variable in order to install additional extensions during container initialization.

I haven't checked it yet, but I'll do it shortly.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, I've just pushed a new release which fixed this issue.

Thanks for the useful feedback!
