### ISSUE TITLE
Recovery code sent, but redirected to undefined

### ISSUE THREAD

**Issue by MrMEEE** [sysPass/plugin-Authenticator#13]
Hi

After getting sent the recovery code, i'm redirected to:

authenticator/checkCode/undefined

to a 404 not found...

Please advice

**Comment by MrMEEE** [comment]
Do you guys need more info???

**Comment by nuxsmin** [comment]
Hello,  no further info is needed, it will be fixed shortly.

Thanks for the feedback!

Regards

**Comment by MrMEEE** [comment]
Thanks a lot.. maybe some documentation on howto use the recovery option would also be nice.. but might be self-explaining, when this gets fixed..

**Comment by MrMEEE** [comment]
Great.. Tested working.. thanks
