### ISSUE TITLE
syspass borks out after plugin install on v3 rc4

### ISSUE THREAD

**Issue by brumle80** [sysPass/plugin-Authenticator#17]
I'm running syspass v3 rc4 without issue without docker, but when I try to add this plugin with composer I get the following issue and syspass breaks until I delete the Authenticator folder in plugins.

https://pastebin.com/raw/Jann1t1D

is it me doing something wrong?

**Comment by nuxsmin** [comment]
Hello, it might be caused by a wrong plugin version, since sysPass v3.1 requires plugin's 2.1 version.

Regards

**Comment by brumle80** [comment]
That makes sense.

It works now that I changed to 2.1 version of the plugin :)
