### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jlebard** [sysPass/plugin-Authenticator#18]
Installation on last release syspass, php7.1 on centos 7.6
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested. 
Package phpunit/dbunit is abandoned, you should avoid using it. No replacement was suggested.

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply...

These packages are related to development dependencies, so you can safely skip them on a production environment. Please check out composer command line to skip these packages.

Regards.
