### ISSUE TITLE
Events 2FA

### ISSUE THREAD

**Issue by Altes** [sysPass/plugin-Authenticator#21]
Hello,
since there isnt an option yet to enforce the 2FA on users, we thought to enforce it "manually" and check that everyone will not disable it by making an alert on our remote syslog at a given event like "user edited the 2FA" or "user removed it".
I know there is an event called "show.userSettings" but that is generated everytime a user click or edit a generic setting, not only the 2FA.

My question: is there a specific event that tells when a user makes a change in the 2FA? 
If not it would be great if it will be implemented in the future releases.

Thank you for the hard work on syspass, its really a great tool 👍 

Regards

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply...

Unfortunately there aren't such kind of events implemented on the plugin, however they can be easily implemented, so they will be available on next plugin's release.

Thanks for the feedback!

Regards
