### ISSUE TITLE
2FA wrong code

### ISSUE THREAD

**Issue by yawnbros** [sysPass/plugin-Authenticator#22]
I have backed up and restored an existing SysPass to a new instance. 2FA is working on the original instance but on the new instance, when I try to enable 2FA and enter the code, it always comes back with "Wrong Code".

I have tried disabled and re-enabling the plugin, resetting the plugin data and using different auth apps all with the same result.

No errors in the SysPass.log.

Google Chrome web browser.

**Comment by yawnbros** [comment]
Plugin version is 2.1 and the SysPass version is 3.1 running on centos 7.

**Comment by yawnbros** [comment]
Selecting the plugin and choosing delete returns the following error:

There was an error
SyntaxError: Unexpected token T in JSON at position 0

Too few arguments to function SP\Modules\Web\Controllers\PluginController::deleteAction(), 0 passed and exactly 1 expected

**Comment by nuxsmin** [comment]
Hello,

plugins cannot be deleted from the UI, they can only be disabled. I've removed that option from the menu.

Thanks for the feedback!
