### ISSUE TITLE
Configurar plugin

### ISSUE THREAD

**Issue by davidkast** [sysPass/plugin-Authenticator#23]
Hola,
he conseguido instalar el plugin en sysPass 3.1 pero no soy capaz de ver como debo de configurar.

## Instalar plugin-authenticator
apt-get install php7.2-xdebug
service apache2 restart

cd /var/www/html/syspass
php composer.phar require syspass/plugin-authenticator:^v2.1

Una vez instalado lo he activado, entiendo que debería de aparecer algún código Qr pero no se donde buscarlo. En el apartado usuario no veo ninguna nueva opción.

Pueden ayudarme?
Gracias.

**Comment by nuxsmin** [comment]
Hola,

disculpa la demora. La configuración del plugin se realiza desde las preferencias del ussuario, ya que cada usuario debe de activar el 2FA mediante el emparejamiento con la aplicación que genera los códigos.

Saludos!
