### ISSUE TITLE
Install plugin Authenticator plugin v2with docker compose , syspass 3.1.2 

### ISSUE THREAD

**Issue by ji8812** [sysPass/plugin-Authenticator#24]
Hello can you give me a step by step to install you plugin please, for docker-compose 3.1.2

thanks a lot

**Comment by OdieArbuckle** [comment]
I'd like to have this too! I keep running into errors, no matter how hard I try or look for the right syntax. Really frustrating!  Any help would be greatly appreciated...

**Comment by ji8812** [comment]
ask the person who did this plugin , i guess youshould try syspass:latest

SSL alsoi have a big issue

**Comment by OdieArbuckle** [comment]
Hi everyone,
I don't exactly know how but I managed to install the plugin!
thx anyway!

**Comment by ji8812** [comment]
via docker-compose?

if so please can you paste your docker compose

i have no issue with install the app on the server. only with docker i have some issues

**Comment by OdieArbuckle** [comment]
Sorry for the late reply...

`version: '2'
services:
  app:
    container_name: syspass-app
    image: syspass/syspass:3.1.0 # Set this version tag to desired one
    restart: always
    # Will listen on ports 80 and 443 of the host
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    volumes:
      - syspass-config:/var/www/html/sysPass/app/config
      - syspass-backup:/var/www/html/sysPass/app/backup
    # Set USE_SSL=no if you're using a LB or reverse proxy for SSL offloading
    environment:
      - USE_SSL=yes
      - COMPOSER_EXTENSIONS=syspass/plugin-authenticator:^v2.1
  db:
    container_name: syspass-db
    restart: always
    image: mariadb:10.2
    # Set a secure password for MariaDB root user
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxxxxxxxxxxxxxx
    # This ports will only be accesible internally
    expose:
      - "3306"
    volumes:
      - syspass-db:/var/lib/mysql

# Persistent volumes to be used across updates
volumes:
  syspass-config: {}
  syspass-backup: {}
  syspass-db: {}
`

**Comment by OdieArbuckle** [comment]
Hi,
Sorry for my late reply.
I thought there would be a nicer way to input this but it's quite plane :-\


`version: '2'
services:
  app:
    container_name: syspass-app
    image: syspass/syspass:3.1.0 # Set this version tag to desired one
    restart: always
    # Will listen on ports 80 and 443 of the host
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    volumes:
      - syspass-config:/var/www/html/sysPass/app/config
      - syspass-backup:/var/www/html/sysPass/app/backup
    # Set USE_SSL=no if you're using a LB or reverse proxy for SSL offloading
    environment:
      - USE_SSL=yes
      - COMPOSER_EXTENSIONS=syspass/plugin-authenticator:^v2.1
  db:
    container_name: syspass-db
    restart: always
    image: mariadb:10.2
    # Set a secure password for MariaDB root user
    environment:
      - MYSQL_ROOT_PASSWORD=Q6SLFd2uPRQ6WSHG
    # This ports will only be accesible internally
    expose:
      - "3306"
    volumes:
      - syspass-db:/var/lib/mysql

#Persistent volumes to be used across updates
volumes:
  syspass-config: {}
  syspass-backup: {}
  syspass-db: {}
`

**Comment by nuxsmin** [comment]
Hello,

@ji8812 did you manage to install it? (https://syspass-doc.readthedocs.io/en/3.1/installing/docker.html#id4)

@OdieArbuckle thanks for your contribution ("```" are helpful ;) )

Regards
