### ISSUE TITLE
Cannot install plugin with composer(non-docker)

### ISSUE THREAD

**Issue by eugengubich** [sysPass/plugin-Authenticator#25]
Hello.

Tried install plugin with `php composer.phar require syspass/plugin-authenticator:^v2.1`, but have an error 

```  Problem 1
    - The requested package phpseclib/phpseclib (locked at 2.0.21, required as ~2.0.25) is satisfiable by phpseclib/phpseclib[2.0.21] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package php-di/php-di (locked at 6.0.9, required as ~6.0.11) is satisfiable by php-di/php-di[6.0.9] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```
Also tried install with php composer.phar require --no-update syspass/plugin-authenticator, but no any plugins appear in Syspass plugins tab.

What I'm doing wrong? Thanks in advance.

**Comment by rob42** [comment]
same problem

**Comment by rob42** [comment]
I manually edited composer.lock to allow compatible (later) versions and composer ran ok but I dont see any plugin when running syspass :-(

**Comment by rob42** [comment]
Ok progress... Previously I used the command `sudo php composer.phar require syspass/plugin-authenticator:^v2.1 --no-plugins --no-scripts --update-no-dev` and it installed some vendor packages but not the plugin. Yeah probably cos I added `--no-plugins` but I'm a java guy, php is a mystery to me.

So I ran `sudo php composer.phar require syspass/plugin-authenticator:^v2.1` and ignored the "Dont run as root" message. The plugin is visible now but have I compromised a critical security system?

Perhaps some more explicit instructions would be good, especially for those of us who are not familiar with php security.

**Comment by neo762** [comment]
php composer.phar require phpseclib/phpseclib php-di/php-di

**Comment by rob42** [comment]
I'm pretty sure phpseclib/phpseclib and php-di/php-di were already installed.

**Comment by neo762** [comment]
> I'm pretty sure phpseclib/phpseclib and php-di/php-di were already installed.

yes, but outdated.

**Comment by eugengubich** [comment]
@neo762 
> php composer.phar require phpseclib/phpseclib php-di/php-di

Thank you, works for me.

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply....

@eugengubich I'm wondering why it's asking for installing these packages, since they're already installed with sysPass. Did you install sysPass dependencies from vendor package instead?

@rob42 
> So I ran sudo php composer.phar require syspass/plugin-authenticator:^v2.1 and ignored the "Dont run as root" message. The plugin is visible now but have I compromised a critical security system?

No, it's all about permissions, since webserver is running using its own user so it could break some functinality...

Regards

**Comment by GHeiner** [comment]
Hello and i hope someone can help me. I use syspass with docker. But i didn't use docker composer, but used the alternative installation with two seperate dockers, it's runnin gok but i can't install the athenticator
 i have this in the log
setup_app: Setting up permissions
setup_composer_extensions: syspass/plugin-authenticator:^v2.1 
~ /var/www/html
run_composer: Running composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package phpseclib/phpseclib (locked at 2.0.21, required as ~2.0.25) is satisfiable by phpseclib/phpseclib[2.0.21] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package php-di/php-di (locked at 6.0.9, required as ~6.0.11) is satisfiable by php-di/php-di[6.0.9] but these conflict with your requirements or minimum-stability.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
Installation failed, reverting ./composer.json to its original content.
/var/www/html
setup_locales: Locales already set up

i use the docker image syspass/syspass:latest

**Comment by nuxsmin** [comment]
Hello,

this issue should be solved in latest releases. Thanks for the feedback!

Regards
