### ISSUE TITLE
Can't install plugin-Authenticator in docker image v3.2.1

### ISSUE THREAD

**Issue by xenofree** [sysPass/plugin-Authenticator#31]
Hi,

I try to install this plugin but it throw me an error everytime.

`version: '2'
services:
  app:
    container_name: syspass-app
    image: syspass/syspass:3.2.1
    restart: always
    ports:
      - "8282:80"
      - "8383:443"
    links:
      - db
    volumes:
      - ./data/syspass-config:/var/www/html/sysPass/app/config
      - ./data/syspass-backup:/var/www/html/sysPass/app/backup
    environment:
      - USE_SSL=yes
      - COMPOSER_EXTENSIONS=syspass/plugin-authenticator:^v2.2
  db:
    container_name: syspass-db
    restart: always
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=syspass
    ports:
      - "3306"
    volumes:
      - ./data/syspass-db:/var/lib/mysql
`

`entrypoint: Starting with UID : 9001
setup_app: Setting up permissions
setup_composer_extensions: syspass/plugin-authenticator:^v2.2
~ /var/www/html
run_composer: Running composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for syspass/extension-installer-plugin v2.0.0 -> satisfiable by syspass/extension-installer-plugin[v2.0.0].
    - syspass/extension-installer-plugin v2.0.0 requires composer-plugin-api ^2.0 -> no matching package found.
  Problem 2
    - syspass/plugin-authenticator v2.2.0 requires syspass/extension-installer-plugin ^2.0 -> satisfiable by syspass/extension-installer-plugin[v2.0.0].
    - syspass/plugin-authenticator v2.2.1 requires syspass/extension-installer-plugin ^2.0 -> satisfiable by syspass/extension-installer-plugin[v2.0.0].
    - syspass/extension-installer-plugin v2.0.0 requires composer-plugin-api ^2.0 -> no matching package found.
    - Installation request for syspass/plugin-authenticator ^v2.2 -> satisfiable by syspass/plugin-authenticator[v2.2.0, v2.2.1].

Potential causes:
 - A typo in the package name                                                                                                                                                                                         - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it                                                                                                                                       
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

Installation failed, reverting ./composer.json to its original content.`

Could you help me on this ?

Regards,

**Comment by t0l0** [comment]
Hi @xenofree,
it seems that the newer version of the extension installer plugin require compose 2.0 while unfortunately the docker image still has composer 1 installed.
You can work around this by overriding the original entrypoint for now:
[docker-compose.yml.txt](https://github.com/sysPass/plugin-Authenticator/files/5912185/docker-compose.yml.txt)

@nuxsmin For the next docker image please consider upgrading composer to version 2 so the authenticator plugin can be installed without a workaround.

**Comment by nuxsmin** [comment]
Hello,

this issue should be solved. Thanks for the feedback!

Regards
