### ISSUE TITLE
Authenticator "Class 'BaconQrCode\Renderer\Image\Png' not found"

### ISSUE THREAD

**Issue by littlebutcher** [sysPass/plugin-Authenticator#32]
Hello,

I have problem with Authenticator ( in Syspass 3.2, Authenticator 2.2.1).
When I enable Authenticator in Plugins, I see in User prefereneces only text "Class 'BaconQrCode\Renderer\Image\Png' not found" nothing else.
When I disable Autheticator in Plugins, It works good, I could set some User preference.
Please how I solve this problem? 
![image](https://user-images.githubusercontent.com/77960131/105682276-8b792100-5ef2-11eb-9fa9-2bcf7a46cb74.png)
Thnaks

**Comment by G4b93** [comment]
Hi,
same issue here with Syspass 3.2 and Authenticator 2.2.1.

Any suggestions?

Thanks

**Comment by tuxudo** [comment]
Version 2.0 of BaconQrCode doesn't include the PNG renderer. See https://github.com/antonioribeiro/google2fa/issues/105

**Comment by ortizleo** [comment]
> Version 2.0 of BaconQrCode doesn't include the PNG renderer. See [antonioribeiro/google2fa#105](https://github.com/antonioribeiro/google2fa/issues/105)

did you make it works?

**Comment by tuxudo** [comment]
Yes, you need to manually download the older 1.0.3 version of BaconQrCode and replace the 2.0 version in vendor with the files from the 1.0.3 version.

**Comment by occom9000** [comment]
Hmm, cant get this to work copying the 1.0.3 version over the 2.0 version, tried forcing compiler to install the 1.0.3 version but no luck.

Any other ideas?

**Comment by occom9000** [comment]
Update:  You dont have to copy over the entire directory, the contents of the BaconQrCode folder into the /src/ folder

So for me (Ubuntu 18.04 lts)

sudo cp -a /tmp/BaconQrCode/. /var/www/html/sysPass-3.2.1/vendor/bacon/bacon-qr-code/src/

and a restart fixed it.
