### ISSUE TITLE
security_pin input should have autofocus

### ISSUE THREAD

**Issue by dvdfabian** [sysPass/plugin-Authenticator#7]
Hello,

the pin input should have autofocus enabled when the 2fa plugin requests a PIN. It is inconvenient to use mouse to focus the field and then start typing. Simply adding the `autofocus` attribute to the element is enough, I think.

Best regards,

David Fabian

**Comment by nuxsmin** [comment]
Hello @dvdfabian ,

 I agree with you, it should gain focus after page loading.

Kind regards
