### ISSUE TITLE
How to make it work with sysPass 3.0 Beta

### ISSUE THREAD

**Issue by vmario89** [sysPass/plugin-Authenticator#9]
Hi,

i tried to install this to the v3 version but it does not work. What i did:

cd /var/www/vhosts/pw.THEDOMAIN.de/app/modules/web/plugins
 git clone https://github.com/nuxsmin/sysPass-Plugins.git
cd sysPass-Plugins
mv * ../
cd ..
rm -rf sysPass-Plugins
cd ..
chown -R www-data:www-data plugins
chmod -R 750 plugins

i gues this does not work due to some structural changes right?

regards, Mario

**Comment by nuxsmin** [comment]
Hi!

Yes, this plugin need to be adapted to the new code structure, since it has changed a lot...

Regards

**Comment by nuxsmin** [comment]
Hi, I've recently worked on  updating the plugin in order to get it working on v3. It could be installed through composer.

There are some improvements like a built-in QR code generator that doesn't need to generate using an external URL.

Regards
